---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: arc-runner-shared-${env_class}
  namespace: arc-runners
spec:
  interval: 12h
  maxHistory: 20
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.4.0
      sourceRef:
        kind: HelmRepository
        name: arc
        namespace: flux-system
  releaseName: pe-arc-runner-shared-${env_class}
  targetNamespace: arc-runners
  values:
    githubConfigSecret: pe-github-secret  #pragma: allowlist secret
    githubConfigUrl: "https://github.com/AnoopHegde"
    runnerGroup: platformengine-runner-group
    template:
      spec:
        imagePullSecrets:
          - name: docker-secret
        containers:
          - command:
              - /home/runner/run.sh
            env:
              - name: DOCKER_HOST
                value: tcp://localhost:2376
              - name: DOCKER_TLS_VERIFY
                value: "1"
              - name: DOCKER_CERT_PATH
                value: /certs/client
              - name: RUNNER_WAIT_FOR_DOCKER_IN_SECONDS
                value: "120"
            image: peacr${env_class}.azurecr.io/pe-actions-runner:main
            imagePullPolicy: Always
            name: runner
            volumeMounts:
              - mountPath: /home/runner/_work
                name: work
              - mountPath: /certs/client
                name: dind-cert
                readOnly: true
          - image: docker:dind
            name: dind
            securityContext:
              privileged: true
            volumeMounts:
              - mountPath: /home/runner/_work
                name: work
              - mountPath: /certs/client
                name: dind-cert
              - mountPath: /home/runner/externals
                name: dind-externals
                  #imagePullSecrets:
          #- name: docker-secret          
        initContainers:
          - args:
              - -r
              - -v
              - /home/runner/externals/.
              - /home/runner/tmpDir/
            command:
              - cp
            image: peacr${env_class}.azurecr.io/pe-actions-runner:main
            name: init-dind-externals
            volumeMounts:
              - mountPath: /home/runner/tmpDir
                name: dind-externals
        volumes:
          - emptyDir: {}
            name: dind-cert
          - emptyDir: {}
            name: dind-externals
          - emptyDir: {}
            name: work
    controllerServiceAccount:
      namespace: arc-systems
      name: pe-arc-controller-gha-runner-scale-set-controller
  install:
    crds: Create
    createNamespace: true
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true


