---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 12h
  maxHistory: 20
  chart:
    spec:
      chart: cert-manager
      version: v1.8.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  releaseName: pe-cert-manager
  targetNamespace: cert-manager
  install:
    crds: Create
    createNamespace: true
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
  values:
    replicaCount: ${replicas}
    installCRDs: true
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
    webhook:
      resources:
        requests:
          cpu: 50m
          memory: 32Mi
    cainjector:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
