apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: arc
  namespace: flux-system
spec:
  interval: 10m
  type: oci  
  url: oci://ghcr.io/actions/actions-runner-controller-charts
