---
ignore:
  - "**/flux-system/"
  - "**/templates/"

yaml-files:
  - "*.yaml"
  - "*.yml"
  - ".yamllint"

rules:
  anchors: disable
  braces: disable
  brackets: disable
  colons: disable
  commas: disable
  comments: disable
    # level: warning
    # min-spaces-from-content: 1
  comments-indentation: disable
  document-end: disable
  document-start: disable
  empty-lines: disable
  empty-values: disable
  float-values: disable
  hyphens: disable
  indentation: disable
  key-duplicates: disable
  key-ordering: disable
  line-length:
    max: 500
    level: warning
  new-line-at-end-of-file: disable
  new-lines:
    type: platform
  octal-values: disable
  quoted-strings: disable
  trailing-spaces: disable
  truthy: disable
