---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: arc
  namespace: arc-systems
spec:
  interval: 12h
  maxHistory: 20
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      version: 0.8.0
      sourceRef:
        kind: HelmRepository
        name: arc
        namespace: flux-system
  releaseName: pe-arc-controller
  targetNamespace: arc-systems
  install:
    crds: Create
    createNamespace: true
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true

