---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: sources
  interval: 1m0s
  path: ./apps/base/cert-manager
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
      #validation: client
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: shared-config
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: cert-manager
          namespace: flux-system
        spec:
          chart:
            spec:
              chart: cert-manager
              version: v1.8.0
      target:
        kind: HelmRelease
