---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-hunter
  namespace: flux-system
spec:
  dependsOn:
    - name: sources
  interval: 1m0s
  path: ./apps/base/kubehunter
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
